blueprint:
  name: ESPHome Buttons
  description: |-
    A Blueprint to handle the events from an ESPHome device with 1 event entity.
  domain: automation
  source_url: https://github.com/jesserockz/blueprints/blob/main/esphome-button-1x.yaml
  input:
    device:
      name: ESPHome Device
      description: Select the ESPHome Device
      selector:
        device:
          multiple: false
          filter:
            - integration: esphome
    button_1:
      name: Button
      icon: mdi:numeric-1-box-outline
      description: Select the actions to perform after an event on the Button
      collapsed: true
      input:
        button_1_single:
          name: Single Click
          default: []
          selector:
            action:
        button_1_double:
          name: Double Click
          default: []
          selector:
            action:
        button_1_four:
          name: Four Clicks
          default: []
          selector:
            action:
        button_1_hold:
          name: Hold
          default: []
          selector:
            action:

trigger_variables:
  deviceid: !input device
  entities: "{{ device_entities(deviceid) }}"

  event_1_entity: >
    {{ entities | selectattr(None, "search", "event.*_button_1") | list | last }}

mode: parallel
trigger:
  - platform: event
    id: one
    event_type: state_changed
    event_data:
      entity_id: "{{ event_1_entity }}"

action:
  - variables:
      action: "{{ trigger.event.data.new_state.attributes.event_type }}"
      button: "{{ trigger.id }}"
  - choose:
      - conditions:
          - condition: trigger
            id:
              - one
        sequence:
          - choose:
              - conditions:
                  - "{{ action == 'click' }}"
                sequence: !input "button_1_single"
              - conditions:
                  - "{{ action == 'double_click' }}"
                sequence: !input "button_1_double"
              - conditions:
                  - "{{ action == 'four_clicks' }}"
                sequence: !input "button_1_four"
              - conditions:
                  - "{{ action == 'hold' }}"
                sequence: !input "button_1_hold"
