blueprint:
  name: ESPHome Buttons
  description: |-
    A Blueprint to handle the events from an ESPHome device with 4 event entities.
  domain: automation
  source_url: https://github.com/jesserockz/blueprints/blob/main/esphome-button-4x.yaml
  input:
    device:
      name: ESPHome Device
      description: Select the ESPHome Device
      selector:
        device:
          multiple: false
          filter:
            - integration: esphome
    button_1:
      name: Button 1
      icon: mdi:numeric-1-box-outline
      description: Select the actions to perform after an event on Button 1
      collapsed: true
      input:
        button_1_single:
          name: Single Click
          default: []
          selector:
            action:
        button_1_double:
          name: Double Click
          default: []
          selector:
            action:
        button_1_four:
          name: Four Clicks
          default: []
          selector:
            action:
        button_1_hold:
          name: Hold
          default: []
          selector:
            action:
    button_2:
      name: Button 2
      icon: mdi:numeric-2-box-outline
      description: Select the actions to perform after an event on Button 2
      collapsed: true
      input:
        button_2_single:
          name: Single Click
          default: []
          selector:
            action:
        button_2_double:
          name: Double Click
          default: []
          selector:
            action:
        button_2_four:
          name: Four Clicks
          default: []
          selector:
            action:
        button_2_hold:
          name: Hold
          default: []
          selector:
            action:
    button_3:
      name: Button 3
      icon: mdi:numeric-3-box-outline
      description: Select the actions to perform after an event on Button 3
      collapsed: true
      input:
        button_3_single:
          name: Single Click
          default: []
          selector:
            action:
        button_3_double:
          name: Double Click
          default: []
          selector:
            action:
        button_3_four:
          name: Four Clicks
          default: []
          selector:
            action:
        button_3_hold:
          name: Hold
          default: []
          selector:
            action:
    button_4:
      name: Button 4
      icon: mdi:numeric-4-box-outline
      description: Select the actions to perform after an event on Button 4
      collapsed: true
      input:
        button_4_single:
          name: Single Click
          default: []
          selector:
            action:
        button_4_double:
          name: Double Click
          default: []
          selector:
            action:
        button_4_four:
          name: Four Clicks
          default: []
          selector:
            action:
        button_4_hold:
          name: Hold
          default: []
          selector:
            action:

trigger_variables:
  deviceid: !input device
  entities: "{{ device_entities(deviceid) }}"

  event_1_entity: >
    {{ entities | selectattr(None, "search", "event.*_button_1") | list | last }}
  event_2_entity: >
    {{ entities | selectattr(None, "search", "event.*_button_2") | list | last }}
  event_3_entity: >
    {{ entities | selectattr(None, "search", "event.*_button_3") | list | last }}
  event_4_entity: >
    {{ entities | selectattr(None, "search", "event.*_button_4") | list | last }}

mode: parallel
trigger:
  - platform: event
    id: one
    event_type: state_changed
    event_data:
      entity_id: "{{ event_1_entity }}"
  - platform: event
    id: two
    event_type: state_changed
    event_data:
      entity_id: "{{ event_2_entity }}"
  - platform: event
    id: three
    event_type: state_changed
    event_data:
      entity_id: "{{ event_3_entity }}"
  - platform: event
    id: four
    event_type: state_changed
    event_data:
      entity_id: "{{ event_4_entity }}"

action:
  - variables:
      action: "{{ trigger.event.data.new_state.attributes.event_type }}"
      button: "{{ trigger.id }}"
  - choose:
      - conditions:
          - condition: trigger
            id:
              - one
        sequence:
          - choose:
              - conditions:
                  - "{{ action == 'click' }}"
                sequence: !input "button_1_single"
              - conditions:
                  - "{{ action == 'double_click' }}"
                sequence: !input "button_1_double"
              - conditions:
                  - "{{ action == 'four_clicks' }}"
                sequence: !input "button_1_four"
              - conditions:
                  - "{{ action == 'hold' }}"
                sequence: !input "button_1_hold"
      - conditions:
          - condition: trigger
            id:
              - two
        sequence:
          - choose:
              - conditions:
                  - "{{ action == 'click' }}"
                sequence: !input "button_2_single"
              - conditions:
                  - "{{ action == 'double_click' }}"
                sequence: !input "button_2_double"
              - conditions:
                  - "{{ action == 'four_clicks' }}"
                sequence: !input "button_2_four"
              - conditions:
                  - "{{ action == 'hold' }}"
                sequence: !input "button_2_hold"
      - conditions:
          - condition: trigger
            id:
              - three
        sequence:
          - choose:
              - conditions:
                  - "{{ action == 'click' }}"
                sequence: !input "button_3_single"
              - conditions:
                  - "{{ action == 'double_click' }}"
                sequence: !input "button_3_double"
              - conditions:
                  - "{{ action == 'four_clicks' }}"
                sequence: !input "button_3_four"
              - conditions:
                  - "{{ action == 'hold' }}"
                sequence: !input "button_3_hold"
      - conditions:
          - condition: trigger
            id:
              - four
        sequence:
          - choose:
              - conditions:
                  - "{{ action == 'click' }}"
                sequence: !input "button_4_single"
              - conditions:
                  - "{{ action == 'double_click' }}"
                sequence: !input "button_4_double"
              - conditions:
                  - "{{ action == 'four_clicks' }}"
                sequence: !input "button_4_four"
              - conditions:
                  - "{{ action == 'hold' }}"
                sequence: !input "button_4_hold"
